
generation:
  model_id: MBZUAI/LaMini-GPT-1.5B
  lr: 0.0003
  epochs: 4
  initial_bs: 32
  # other model to use next for bigger trials
  # model_id = 'facebook/opt-350m'

data:
  subset: no   # Used for debug. If no, the following will be ignored
  subset_size: 30
