# togethercomputer/RedPajama-INCITE-Chat-3B-v1

generation:
  model_id: togethercomputer/RedPajama-INCITE-Chat-3B-v1
  lr: 0.0003
  epochs: 3
  initial_bs: 16
  dtype: 8-bit    # for toxicity meter
  custom_prompt:
    user_name: '<human>:'
    bot_name: '<bot>:'
  # temp generation config: TODO: find the best one
  generation_config:
    max_new_tokens: 256
    min_new_tokens: 4
    do_sample: yes
    # num_beams: 4
    early_stopping: no
    temperature: 0.7
    top_p: 0.7
    top_k: 50

data:
  subset: no   # Used for debug. If no, the following will be ignored
  subset_size: 30
