# togethercomputer/RedPajama-INCITE-Chat-3B-v1

generation:
  model_id: togethercomputer/RedPajama-INCITE-Chat-3B-v1
  lr: 0.0003
  epochs: 3
  initial_bs: 16
  custom_prompt:
    user_name: '<human>:'
    bot_name: '<bot>:'

data:
  subset: no   # Used for debug. If no, the following will be ignored
  subset_size: 30
